---
- name: Remove VLAN from an interface on IOS box
  ios_vlan:
    vlan_id: "{{ vlan }}"
    state: absent
    associated_interfaces: "{{ item }}"
  with_items:
    "{{ interfaces }}"
  when: ansible_network_os == "ios"

- name: Remove VLAN from an interface on NXOS box
  nxos_vlan:
    vlan_id: "{{ vlan }}"
    state: absent
    associated_interfaces: "{{ item }}"
  with_items:
    "{{ interfaces }}"
  when: ansible_network_os == "nxos"